### ISSUE TITLE
My CPU is AMD. I don't know if it can be recognized normally. I want to use the VMM, but if the CPU is not recognized, the VMM can only use inter virtualization

### ISSUE THREAD

**Issue by ghost** [FOXBI/ch_cpuinfo#10]
![image](https://user-images.githubusercontent.com/50038957/97097733-36d5c800-16af-11eb-9e61-d3502bd07fa2.png)

**Comment by zygds** [comment]
![image](https://user-images.githubusercontent.com/50038957/97097786-122e2000-16b0-11eb-9385-61ee0ada0daa.png)

**Comment by FOXBI** [comment]
may be.. i think fixed at v2.3.2-r01
