### ISSUE TITLE
integer expression expected error

### ISSUE THREAD

**Issue by Lancean** [FOXBI/ch_cpuinfo#11]
Whenever i try to run the application it posts the following

![ch_cpuinfo](https://user-images.githubusercontent.com/77081454/103833037-30d16f80-5080-11eb-9991-30c2216bacef.png)

My hardware is maybe not the usual as i run dual Xeon L5640 with 96GB of ram.

**Comment by FOXBI** [comment]
may be.. i think fixed at v2.3.2-r01

check please.
