### ISSUE TITLE
Please support the display of the i7-4750HQ ES

### ISSUE THREAD

**Issue by sweetstzw** [FOXBI/ch_cpuinfo#12]
Getting SMBIOS data from sysfs.
SMBIOS 2.7 present.

Handle 0x0004, DMI type 4, 48 bytes
Processor Information
        Socket Designation: CPU 0
        Type: Central Processor
        Family: Unknown
        Manufacturer: GenuineIntel
        ID: C2 06 03 00 FF FB 8B 0F
        Version: Genuine Intel(R) CPU 0000 @ 2.00GHz
        Voltage: 3.3 V
        External Clock: Unknown
        Max Speed: 1907 MHz
        Current Speed: 1907 MHz
        Status: Populated, Enabled
        Upgrade: ZIF Socket
        L1 Cache Handle: Not Provided
        L2 Cache Handle: Not Provided
        L3 Cache Handle: Not Provided
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Core Count: 1
        Core Enabled: 1
        Characteristics:
                64-bit capable
                Execute Protection

Handle 0x0005, DMI type 4, 48 bytes
Processor Information
        Socket Designation: CPU 1
        Type: Central Processor
        Family: Unknown
        Manufacturer: GenuineIntel
        ID: C2 06 03 00 FF FB 8B 0F
        Version: Genuine Intel(R) CPU 0000 @ 2.00GHz
        Voltage: 3.3 V
        External Clock: Unknown
        Max Speed: 1907 MHz
        Current Speed: 1907 MHz
        Status: Populated, Enabled
        Upgrade: ZIF Socket
        L1 Cache Handle: Not Provided
        L2 Cache Handle: Not Provided
        L3 Cache Handle: Not Provided
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Core Count: 1
        Core Enabled: 1
        Characteristics:
                64-bit capable
                Execute Protection

Handle 0x0006, DMI type 4, 48 bytes
Processor Information
        Socket Designation: CPU 2
        Type: Central Processor
        Family: Unknown
        Manufacturer: GenuineIntel
        ID: C2 06 03 00 FF FB 8B 0F
        Version: Genuine Intel(R) CPU 0000 @ 2.00GHz
        Voltage: 3.3 V
        External Clock: Unknown
        Max Speed: 1907 MHz
        Current Speed: 1907 MHz
        Status: Populated, Enabled
        Upgrade: ZIF Socket
        L1 Cache Handle: Not Provided
        L2 Cache Handle: Not Provided
        L3 Cache Handle: Not Provided
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Core Count: 1
        Core Enabled: 1
        Characteristics:
                64-bit capable
                Execute Protection

Handle 0x0007, DMI type 4, 48 bytes
Processor Information
        Socket Designation: CPU 3
        Type: Central Processor
        Family: Unknown
        Manufacturer: GenuineIntel
        ID: C2 06 03 00 FF FB 8B 0F
        Version: Genuine Intel(R) CPU 0000 @ 2.00GHz
        Voltage: 3.3 V
        External Clock: Unknown
        Max Speed: 1907 MHz
        Current Speed: 1907 MHz
        Status: Populated, Enabled
        Upgrade: ZIF Socket
        L1 Cache Handle: Not Provided
        L2 Cache Handle: Not Provided
        L3 Cache Handle: Not Provided
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Part Number: Not Specified
        Core Count: 1
        Core Enabled: 1
        Characteristics:
                64-bit capable
                Execute Protection
**cat /proc/cpuinfo**
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Genuine Intel(R) CPU 0000 @ 2.00GHz
stepping        : 2
microcode       : 0xffff0006
cpu MHz         : 1999.813
cache size      : 6144 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                                                                               pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc                                                                                                                                               arch_perfmon nopl xtopology nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_                                                                                                                                              1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hyperv                                                                                                                                              isor lahf_lm abm invpcid_single fsgsbase tsc_adjust avx2 smep invpcid xsaveopt a                                                                                                                                              rat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds                                                                                                                                               swapgs
bogomips        : 3999.62
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Genuine Intel(R) CPU 0000 @ 2.00GHz
stepping        : 2
microcode       : 0xffff0006
cpu MHz         : 1999.813
cache size      : 6144 KB
physical id     : 2
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                                                                               pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc                                                                                                                                               arch_perfmon nopl xtopology nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_                                                                                                                                              1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hyperv                                                                                                                                              isor lahf_lm abm invpcid_single fsgsbase tsc_adjust avx2 smep invpcid xsaveopt a                                                                                                                                              rat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds                                                                                                                                               swapgs
bogomips        : 4014.14
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Genuine Intel(R) CPU 0000 @ 2.00GHz
stepping        : 2
microcode       : 0xffff0006
cpu MHz         : 1999.813
cache size      : 6144 KB
physical id     : 4
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                                                                               pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc                                                                                                                                               arch_perfmon nopl xtopology nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_                                                                                                                                              1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hyperv                                                                                                                                              isor lahf_lm abm invpcid_single fsgsbase tsc_adjust avx2 smep invpcid xsaveopt a                                                                                                                                              rat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds                                                                                                                                               swapgs
bogomips        : 4015.58
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Genuine Intel(R) CPU 0000 @ 2.00GHz
stepping        : 2
microcode       : 0xffff0006
cpu MHz         : 1999.813
cache size      : 6144 KB
physical id     : 6
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov                                                                                                                                               pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc                                                                                                                                               arch_perfmon nopl xtopology nonstop_tsc pni pclmulqdq ssse3 fma cx16 pcid sse4_                                                                                                                                              1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hyperv                                                                                                                                              isor lahf_lm abm invpcid_single fsgsbase tsc_adjust avx2 smep invpcid xsaveopt a                                                                                                                                              rat
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds                                                                                                                                               swapgs
bogomips        : 4020.72
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management:

**Comment by FOXBI** [comment]
your cpu model name is "Genuine Intel(R) CPU 0000 @ 2.00GHz"

It cannot be resolved because the system did not recognize it.
