### ISSUE TITLE
g4600 fails to show

### ISSUE THREAD

**Issue by no1ajian** [FOXBI/ch_cpuinfo#13]
Thanks for the tool!
My 918+ Xpenology shows "INTEL Celeron J3455 undefined" after running ch_cpuinfo

"cat /proc/cpuinfo | grep model" shows 

model           : 158
model name      : Intel(R) Pentium(R) CPU G4600 @ 3.60GHz
model           : 158
model name      : Intel(R) Pentium(R) CPU G4600 @ 3.60GHz
model           : 158
model name      : Intel(R) Pentium(R) CPU G4600 @ 3.60GHz
model           : 158
model name      : Intel(R) Pentium(R) CPU G4600 @ 3.60GHz

what can I do to display its real info?

**Comment by FOXBI** [comment]
fixed
