### ISSUE TITLE
version 정보 관련 문의

### ISSUE THREAD

**Issue by olions** [FOXBI/ch_cpuinfo#2]
해당 버젼 정보는 Changelog로 통합 관리 하는게 어떨까요!?

- [x] Version Info Changelog 통합 관리 

https://github.com/FOXBI/ch_cpuinfo/blob/7b511a4e33638a18af2bb235611aadc1991d4e0e/ch_cpuinfo_ko.sh#L2-L8

**Comment by FOXBI** [comment]
업데이트시 반영하겠습니다.
