### ISSUE TITLE
Marvell Armada 385 

### ISSUE THREAD

**Issue by raydoom** [FOXBI/ch_cpuinfo#28]
my cpu is Marvell Armada 385
```
root@wdmcmg2:/volume1/nfs# cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 2655.84
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x4
CPU part	: 0xc09
CPU revision	: 1

processor	: 1
model name	: ARMv7 Processor rev 1 (v7l)
BogoMIPS	: 2655.84
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x4
CPU part	: 0xc09
CPU revision	: 1

Hardware	: Marvell Armada 380/381/382/383/384/385/388 (Device Tree)
Revision	: 0000
Serial		: 0000000000000000
```
but it is display `Intel ARMv7`

**Comment by FOXBI** [comment]
Thanks for the information. There are sources for output other than Intel and AMD, but the latest version doesn't output at all?

**Comment by raydoom** [comment]
![image](https://user-images.githubusercontent.com/26057967/135458699-c86eddfb-be69-4f0a-96d8-8516a944d2fc.png)

**Comment by FOXBI** [comment]
Oops!  It's not like this Intel, but Intel is attached!!!

I will make sure to reflect the changes.

thank you for the information.!!

**Comment by raydoom** [comment]
thank you, and the system temperature also can not display, have a idea?

**Comment by raydoom** [comment]
And my device is wd mycloud mirror gen2, is like DS216

**Comment by FOXBI** [comment]
v4.0.0-r01

It has been changed to be able to output information on CPUs other than Intel/AMD.
