### ISSUE TITLE
Hi, not working after updated to 6.2.2﻿-24922

### ISSUE THREAD

**Issue by shirh19910112** [FOXBI/ch_cpuinfo#3]

**Comment by Papyy** [comment]
+1

**Comment by agisofttm** [comment]
+1 

It doesn't work on DSM 6.2.2-24922.
(Jun's Loader v1.03b DS3615 // Asrock E3C226D2I)

**Comment by FOXBI** [comment]
update complete!!! ch_cpuinfo v1.1.0-r01 download available !! Thank you!
