### ISSUE TITLE
Intel i3 M380  Model is not displayed

### ISSUE THREAD

**Issue by host2318** [FOXBI/ch_cpuinfo#32]
root@mynas:/volume1/e# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 37
model name      : Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz
stepping        : 5
microcode       : 0x3
cpu MHz         : 933.000
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes

****************************************************
![image](https://user-images.githubusercontent.com/30349081/154557265-deb4cc2c-e1dc-4394-9546-136d9035ea96.png)

**Comment by FOXBI** [comment]
It is specific to CPU information. It cannot be searched by that name on ark.intel.com.

If you give more information that is searched on ark.intel.com

I will try to reflect it in the next update.

**Comment by host2318** [comment]
> It is specific to CPU information. It cannot be searched by that name on ark.intel.com.
> 
> If you give more information that is searched on ark.intel.com
> 
> I will try to reflect it in the next update.

m380 ark.intel link:
https://ark.intel.com/content/www/us/en/ark/products/50178/intel-core-i3380m-processor-3m-cache-2-53-ghz.html

**Comment by FOXBI** [comment]
4.0.0-r01

Reflected so that model information can be accurately recalled.
