### ISSUE TITLE
CPU model displays incorrectly with 12th Gen Intel Core CPU

### ISSUE THREAD

**Issue by jellybean13** [FOXBI/ch_cpuinfo#33]
ash-4.4# cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 151
model name	: 12th Gen Intel(R) Core(TM) i7-12700
stepping	: 2
microcode	: 0x1e
cpu MHz		: 2111.719
cache size	: 25600 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 32
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 arat pku md_clear flush_l1d arch_capabilities
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs
bogomips	: 4223.43
clflush size	: 64
cache_alignment	: 64
address sizes	: 45 bits physical, 48 bits virtual
power management:

![image](https://user-images.githubusercontent.com/46275808/167248071-47878b81-d59a-4983-9656-b37debf7bda3.png)

**Comment by FOXBI** [comment]
It seems that the 12th gen string is added to the CPU information.

I will try to reflect it in the next update.

Do you know from what generation it is expressed like that? I am using 3th gen, so there is no information.

**Comment by jellybean13** [comment]
> It seems that the 12th gen string is added to the CPU information.
> 
> I will try to reflect it in the next update.
> 
> Do you know from what generation it is expressed like that? I am using 3th gen, so there is no information.

All 12th Gen Intel(R) Core(TM) CPU, including i5-12400, i7-12700, i9-12900, are affected owing to the change of naming policy.

**Comment by FOXBI** [comment]
v4.0.0-r01

Reflected so that model information can be accurately recalled.
