### ISSUE TITLE
DSM 7.1.1-42962 Update 2    更新后，出错了。。。

### ISSUE THREAD

**Issue by hulang** [FOXBI/ch_cpuinfo#36]
7.0 OK.。不支持  7.1.........求大神更新

**Comment by zeuero** [comment]
![微信截图_20221124134329](https://user-images.githubusercontent.com/30445960/203703518-c722ba85-3938-425a-bb26-655576c32b80.png)

**Comment by hulang** [comment]
有一次更新后。我重启电脑，系统都无法启动。。只有一次。。。
