### ISSUE TITLE
G1620T on DS3622+ DSM 7.1.1-42962 Update3 does not work 

### ISSUE THREAD

**Issue by Jedd1996** [FOXBI/ch_cpuinfo#38]
3.1.1 All modes fail
![1](https://user-images.githubusercontent.com/120978257/208314545-9a51e836-e49f-4ed9-bccd-002fd2fc2310.png)
![2](https://user-images.githubusercontent.com/120978257/208314601-e15024b6-0bfe-4787-bfde-65c16d5488ad.png)

**Comment by Jedd1996** [comment]
corrections:3.3.1 r01

**Comment by lukemin** [comment]
input y in lowercase
