### ISSUE TITLE
i3 4130 时钟频率显示不正确

### ISSUE THREAD

**Issue by lukemin** [FOXBI/ch_cpuinfo#39]
cat /proc/cpuinfo
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz
stepping	: 9
microcode	: 0x20
cpu MHz		: 3400.000
cache size	: 3072 KB
但显示的是 1.6G

**Comment by FOXBI** [comment]
v4.0.0-r01

Reflected so that model information can be accurately recalled.
