### ISSUE TITLE
AMD Ryzen 3 PRO 2200GE DSM 7.1.1-42962 Update 2 can not patch

### ISSUE THREAD

**Issue by bobbyvont** [FOXBI/ch_cpuinfo#40]
DSM CPU Information Change Tool ver. 3.3.1-r01 - made by FOXBI

Your version of DSM is DSM 7.1.1-42962 Update 2

The CPU information to be applied is as follows.

AMD Ryzen 3 PRO 2200GE w/ Radeon Vega  Graphics [4 Cores (1 CPU/4 Cores | 4 Threads)] continue...

1) First run  2) Redo  3) Restore - Select Number : 2

Do you want to proceed again? Restore to original file backup and proceed.(Cancel : q) [y/n] : y

You have verified and installed the previous version. Contiue...

Auto Excute, If you select n, proceed interactively  (Cancel : q) [y/n] : y

Restore to Original Source and Continue.

sed: -e expression #1, char 85: unknown option to `s'
sed: -e expression #1, char 135: unknown option to `s'
The operation is complete!! It takes about 1-2 minutes to reflect,
(Please refresh the DSM page with F5 or after logout/login and check the information.)

**Comment by bobbyvont** [comment]
MODEL:DS923+

**Comment by FOXBI** [comment]
v4.0.0-r01

Reflected so that model information can be accurately recalled.

**Comment by bobbyvont** [comment]
Thank you for replying and updating patch, i used v4.0.0-r01 log display can not patch
./ch_cpuinfo
DSM CPU Information Change Tool ver. 3.3.1-r01 - made by FOXBI

Your version of DSM is DSM 7.1.1-42962 Update 2  

The CPU information to be applied is as follows.

AMD Ryzen 3 PRO 2200GE w/ Radeon Vega  Graphics [4 Cores (1 CPU/4 Cores | 4 Threads)] continue...

1) First run  2) Redo  3) Restore - Select Number : 2
 
Do you want to proceed again? Restore to original file backup and proceed.(Cancel : q) [y/n] : y

You have verified and installed the previous version. Contiue...

Auto Excute, If you select n, proceed interactively  (Cancel : q) [y/n] : y

Restore to Original Source and Continue.

sed: -e expression #1, char 85: unknown option to `s'
sed: -e expression #1, char 135: unknown option to `s'
The operation is complete!! It takes about 1-2 minutes to reflect, 
(Please refresh the DSM page with F5 or after logout/login and check the information.)

xpenlib(cpu_info.sh) refered https://github.com/FOXBI/xpenlib/blob/main/cpu_info.sh
run ./cpu_info.sh 
./cpu_info.sh: line 8: syntax error near unexpected token `newline'
./cpu_info.sh: line 8: `<!DOCTYPE html>'
