### ISSUE TITLE
can't work with dsm 6.2.3

### ISSUE THREAD

**Issue by Yuyuko-sama** [FOXBI/ch_cpuinfo#6]
It seems dsm 6.2.3 change h.cpu to g.cpu, it also change some formats.
QAQ hope someone can fix it .

**Comment by tanst** [comment]
But the mobile web is right on dsm 6.2.3
看来6.2.3还不稳定

**Comment by FOXBI** [comment]
update ch_cpuinfo complete!!

you can do download v2.2.1-r01

thank you!!
